# Generated by Django 3.1.3 on 2021-02-16 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0007_auto_20210121_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('ecpt', models.IntegerField(default=0)),
                ('major', models.IntegerField(default=0)),
                ('ppe', models.IntegerField(default=0)),
                ('hus', models.IntegerField(default=0)),
                ('other_humanity', models.IntegerField(default=0)),
                ('core_eng1', models.IntegerField(default=0)),
                ('core_eng2', models.IntegerField(default=0)),
                ('core_writing', models.IntegerField(default=0)),
                ('core_math1', models.IntegerField(default=0)),
                ('core_math2', models.IntegerField(default=0)),
                ('core_science', models.IntegerField(default=0)),
                ('core_exp', models.IntegerField(default=0)),
                ('music', models.IntegerField(default=0)),
                ('exercise', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
