# Generated by Django 3.1.3 on 2021-02-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_graduation_uploadfilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduation',
            name='core_eng1',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='core_eng2',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='core_exp',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='core_math1',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='core_math2',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='core_science',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='core_writing',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='ecpt',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='hus',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='major',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='music',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='other_humanity',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='ppe',
        ),
        migrations.RemoveField(
            model_name='graduation',
            name='result',
        ),
        migrations.AddField(
            model_name='graduation',
            name='my_major',
            field=models.CharField(choices=[('0', 'physics_core'), ('6', 'environment_core'), ('2', 'biology_core'), ('1', 'chemical_core'), ('5', 'material_core'), ('3', 'eecs_core'), ('4', 'mechanics_core')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
