# Generated by Django 3.1.3 on 2021-02-22 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0009_auto_20210222_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduation',
            name='my_major',
            field=models.CharField(choices=[('2', 'biology_core'), ('3', 'eecs_core'), ('6', 'environment_core'), ('1', 'chemical_core'), ('5', 'material_core'), ('0', 'physics_core'), ('4', 'mechanics_core')], max_length=20),
        ),
    ]
