# Generated by Django 3.1.3 on 2021-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_auto_20210222_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='my_major',
            field=models.CharField(choices=[('5', 'material_core'), ('6', 'environment_core'), ('2', 'biology_core'), ('0', 'physics_core'), ('4', 'mechanics_core'), ('3', 'eecs_core'), ('1', 'chemical_core')], max_length=20),
        ),
    ]
