# Generated by Django 3.1.3 on 2021-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_auto_20210223_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='my_major',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
