# Generated by Django 3.1.3 on 2021-03-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_auto_20210223_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graduation',
        ),
    ]
